# Site
name: "Budidaya Tani"
title: "Budidaya Tani"
description: "Portal Informasi Pertanian, Peternakan"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'budidayatani'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title

# Authors
authors:
  Yudi Anto:
    name: Yudianto
    display_name: Yudianto
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://linktr.ee/yudiant0
    twitter: https://twitter.com/wowthemesnet
    orcid: https://orcid.org/0000-0001-9836-4408
    description: "Yudianto adalah seorang penulis di Budidayatani dan Mitrausahatani.com. Ia memiliki hobi di bidang pertanian dan sering menulis artikel terkait teknik budidaya tanaman dan usaha tani. Yudianto berkontribusi dengan berbagi pengetahuan dan pengalaman untuk mendukung pertanian yang berkelanjutan dan inovatif"
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-8729047969381938"
adsense-data-ad-slot: "9444738422"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
